version: 1.0.{build}

image: Visual Studio 2017
environment:
  test_var: test
    
install:
  - nuget restore
  
artifacts:
- path: ./LinuxConsoleApp/**/*.dll
  name: allArtifacts
- path: package.zip
  name: packagedArtifacts
build:
  project: LinuxConsoleApp.sln
  #publish_wap: true
after_build:
  - ps: |
          $artifactPaths = ''
          foreach ($artifactName in $artifacts.keys) { 
            write-host $artifactName
            artifactPaths += $artifacts[$artifactName].path 
            artifactPaths += \s
           
            7z a package.zip $artifacts[$artifactName].path
          }
          write-host $artifactPaths
