
-
  branches:
    only: 
      - test
  version: 1.0.{build}

  image: Visual Studio 2017

  environment:
    test_var: test
  install:
    - ps: |
        [environment]::GetEnvironmentVariable("PATH","Machine").split(";")
    - echo %xunit20%
    
  build:
    project: LinuxConsoleApp.sln
-
  version: 1.0.{build}

  image: Visual Studio 2017

  environment:
    test_var: test
  only_commits:
    files: 
      - README.md
  after_test:
    - echo "after test!!"


