version: 1.0.{build}

image: Visual Studio 2017
environment:
  test_var: test
    
install:
  - nuget restore
  
artifacts:
- path: ./LinuxConsoleApp/**/*.dll
  name: allArtifacts
- path: package.zip
  name: packagedArtifacts
build:
  project: LinuxConsoleApp.sln
  #publish_wap: true
after_build:
  - ps: |
      foreach ($artifactValue in $artifacts.values) {
         7z a package.zip $artifactValue
      }
deploy_script: 
  - ps: | 
          $artifacts.count
          foreach ($artifactName in $artifacts.keys) {             
            $artifacts[$artifactName]
          }
