version: 1.0.{build}
image: Visual Studio 2017

install:
  - ps: |
  
    Write-Host "Installing GitVersion 3.6.5..." -ForegroundColor Cyan
    $gvPath = "$env:SYSTEMDRIVE\Tools\GitVersion"
    if(Test-Path $gvPath) {
        del $gvPath -Recurse -Force
    }

    $tempPath = "$env:USERPROFILE\GitVersion"
    nuget install gitversion.commandline -version 3.6.5 -excludeversion -outputdirectory $tempPath

    [IO.Directory]::Move("$tempPath\gitversion.commandline\tools", $gvPath)
    del $tempPath -Recurse -Force
    Add-Path $gvPath
    Write-Host "GitVersion 3.6.5 installed" -ForegroundColor Green
  - nuget restore
  #- ps: |
   #   [environment]::GetEnvironmentVariable("PATH","Machine").split(";")
  - echo %xunit20%    
build: 
 project: LinuxConsoleApp.sln
 #publish_aspnet_core: true


for:
  -
    branches:
      only: 
        - test
    only_commits:
      files: 
         - README.md
    version: 1.0.{build}

    image: Visual Studio 2017

    environment:
      test_var: test
    install:
      - echo "in test branch"
