version: 1.0.{build}

image: Visual Studio 2017
environment:
  test_var: test
    
install:
  - nuget restore
  
artifacts:
- path: LinuxConsoleApp\**\*.dll


build:
  project: LinuxConsoleApp.sln

before_deploy:
  - ps: |
          $artifactPaths = ''
          foreach ($artifactName in $artifacts.keys) { 
            $artifacts[$artifactName]
            7z a package.zip $artifacts[$artifactName].path
            $artifactPaths += $artifacts[$artifactName].path
          }
          write-host $artifactPaths
          
  - appveyor PushArtifact package.zip 
          
deploy_script: 
  - ps: | 
          $artifacts.count
          foreach ($artifactName in $artifacts.keys) {             
            $artifacts[$artifactName]
          }
