version: 1.0.{build}

image: 
  #- Visual Studio 2013
  #- Visual Studio 2015
  #- Visual Studio 2017
  - Ubuntu

build: false

install:
  - curl -L https://aka.ms/win32-x64-user-stable -v
  - ps: rm Alias:wget
  - ps: choco install wget
  - wget www.google.com
