version: 1.0.{build}

image: Visual Studio 2017
environment:
  test_var: test
    
install:
  - nuget restore
  
artifacts:
- path: package.zip
  name: allArtifacts
  
build:
  project: LinuxConsoleApp.sln
  #publish_wap: true
after_build:
  - 7z a package.zip %APPVEYOR_BUILD_FOLDER%/LinuxConsoleApp/**/*.dll
deploy_script: 
  - ps: | 
          $artifacts.count
          foreach ($artifactName in $artifacts.keys) {             
            $artifacts[$artifactName]
          }
