version: 1.0.{build}

image: Visual Studio 2017

environment:
  test_var: test
-
  branches:
    only: 
      - test
  
  install:
    - ps: |
        [environment]::GetEnvironmentVariable("PATH","Machine").split(";")
    - echo %xunit20%
    
  build:
    project: LinuxConsoleApp.sln
-
  only_commits:
    files: 
      - README.md
  after_test:
    - echo "after test!!"


