version: 1.0.{build}

image: Visual Studio 2017

#init:
 # - sh: echo $APPVEYOR_BUILD_NUMBER
  #- sh: a=`expr 1 - 1` && if [[ $a == 0 ]]; then echo $a; fi
  

environment:
  test_var: test
    
install:
  #- echo "changed"
  - ps: |
      & "C:\Program Files\Amazon\AWSCLI\aws.exe" --version
  - nuget restore
  #- ps: |
   #   [environment]::GetEnvironmentVariable("PATH","Machine").split(";")
  - echo %xunit20%    
  #- cd ..
  #- ls
  #- cd $APPVEYOR_BUILD_FOLDER
  #- $APPVEYOR_BUILD_FOLDER
  - nuget restore
  
artifacts:
- path: LinuxConsoleApp\bin\**\*\

build:
  project: LinuxConsoleApp.sln
  publish_wap: true
  
before_deploy:
  - ps: |
          $artifactPaths = ''
          foreach ($artifactName in $artifacts.keys) { 
            $artifacts[$artifactName]
            7z a package.zip $artifacts[$artifactName].path
            $artifactPaths += $artifacts[$artifactName].path
          }
          write-host $artifactPaths
          
  - appveyor PushArtifact package.zip 
          
deploy_script: 
  - ps: | 
          $artifacts.count
          foreach ($artifactName in $artifacts.keys) {             
            $artifacts[$artifactName]
          }
