version: 1.0.{build}

image: 
  #- Visual Studio 2013
  #- Visual Studio 2015
  #- Visual Studio 2017
  - Ubuntu

build: false

install:
  - if [ -f "/tmp/build-cache-logs/f1135c1a0edcf36d1afbbd802a2cda099204cf1c.zip.001.log" ]; then cat /tmp/build-cache-logs/f1135c1a0edcf36d1afbbd802a2cda099204cf1c.zip.001.log; fi
  - sudo apt-get -f install haskell-stack
  - ls /var/cache/apt/archives/haskell-stack_0.1.10.0-1_amd64.deb
  #- curl -L https://download.microsoft.com/download/E/8/A/E8AF2EE0-5DDA-4420-A395-D1A50EEFD83E/dotnet-sdk-2.1.401-win-x64.exe -v -o dotnetSDK.exe
  #- cat /etc/hosts
  #- curl -L http://web.archive.org
  #- dir
  #- ps: rm Alias:wget
  #- ps: choco install wget
  #- wget www.google.com
artifacts:
  - path: /var/tmp/build-cache-logs/*.log
    name: log.txt
cache:
  - C:\ProgramData\chocolatey\lib
  - /var/cache/apt/archives/haskell-stack_0.1.10.0-1_amd64.deb/ -> appveyor.yml
 
