version: 1.0.{build}

image: Ubuntu
environment:
  test_var: test
    
install:
  - nuget restore
  
artifacts:
- path: ./LinuxConsoleApp/**/*
  name: allArtifacts
  
build:
  project: LinuxConsoleApp.sln
  #publish_wap: true

deploy_script: 
  - ps: | 
          $artifacts.count
          foreach ($artifactName in $artifacts.keys) {             
            $artifacts[$artifactName]
          }
