version: 1.0.{build}

image: 
  - Visual Studio 2013
  - Visual Studio 2015
  - Visual Studio 2017


build: false

install:
  #- ps: rm Alias:wget
  - ps: choco install wget
  - ps: wget www.google.com
