version: 1.0.{build}

image: Ubuntu

init:
  - sh: echo $APPVEYOR_BUILD_NUMBER
  - sh: a=`expr $APPVEYOR_BUILD_NUMBER % 2` && if [[ $a != 5 ]]; then echo $a; fi
  #- sh: appveyor exit

environment:
  test_var: test
    
install:
  #- cd ..
  #- ls
  #- cd $APPVEYOR_BUILD_FOLDER
  #- $APPVEYOR_BUILD_FOLDER
  - nuget restore
  
artifacts:
- path: LinuxConsoleApp\bin\**\*\

build:
  project: LinuxConsoleApp.sln
  publish_wap: true
  
before_deploy:
  - ps: |
          $artifactPaths = ''
          foreach ($artifactName in $artifacts.keys) { 
            $artifacts[$artifactName]
            7z a package.zip $artifacts[$artifactName].path
            $artifactPaths += $artifacts[$artifactName].path
          }
          write-host $artifactPaths
          
  - appveyor PushArtifact package.zip 
          
deploy_script: 
  - ps: | 
          $artifacts.count
          foreach ($artifactName in $artifacts.keys) {             
            $artifacts[$artifactName]
          }
