version: 1.0.{build}

image: Visual Studio 2017
environment:
  test_var: test
    
install:
  - nuget restore
  
artifacts:
- path: ./LinuxConsoleApp/**/*.dll
  name: allArtifacts
- path: package.zip
  name: packagedArtifacts
build:
  project: LinuxConsoleApp.sln

before_deploy:
  - ps: |
          $artifactPaths = ''
          foreach ($artifactName in $artifacts.keys) { 
            write-host $artifactName.name
            $artifactPaths += $artifacts[$artifactName].path 
            $artifactPaths += ' '
          }
          write-host $artifactPaths
          7z a package.zip $artifactsPaths
          
deploy_script: 
  - ps: | 
          $artifacts.count
          foreach ($artifactName in $artifacts.keys) {             
            $artifacts[$artifactName]
          }
