version: 1.0.{build}
image: Visual Studio 2017
install:
  - ps: |
      [environment]::GetEnvironmentVariable("PATH","Machine").split(";")
  - echo %xunit20%    
build: off

for:
  -
    branches:
      only: 
        - test
    only_commits:
      files: 
         - README.md
    version: 1.0.{build}

    image: Visual Studio 2017

    environment:
      test_var: test
    install:
      - echo "in test branch"
