version: 1.0.{build}

image: Visual Studio 2017

environment:
  test_var: test
    
install:
  - nuget restore
  
artifacts:
- path: ./**/*
  name: allArtifacts
  
build:
  project: LinuxConsoleApp.sln
  #publish_wap: true

deploy_script: 
  - ps: | 
          write-host $artifacts
          foreach ($artifactName in $artifacts.keys) { 
            write-host "count"
            Write-Host $artifacts[$artifactName].name
          }
