-
  branches:
    only: 
      - test-fake
  version: 1.0.{build}
  image: Visual Studio 2017

  environment:
    test_var: test
  build: off
   #project: LinuxConsoleApp.sln
  install:
    - echo "in test branch"  
-
  branches:
    only: 
      - master
  version: 1.0.{build}

  image: Visual Studio 2017
  build:
    project: LinuxConsoleApp.sln
  environment:
    test_var: test
  install:
    - echo "in master branch"
